version: "3"
services:
  solveforall-client:
    image: panupongkeawkam/solveforall-client
    build: .
    container_name: solveforall-client
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
