version: "3"
services:
    deployment:
        image: pithawatnuckong/solve-for-all-server
        container_name: solve-for-all-container
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - $PORT:$PORT
